apiVersion: v1
kind: ConfigMap
metadata:
  name: alexp-config
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresuser
---
apiVersion: v1
kind: Secret
metadata:
  name: alexp-secret
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXNwYXNz
  DATABASE_URI_POSTGRESQL: cG9zdGdyZXNxbDovL3Bvc3RncmVzdXNlcjpwb3N0Z3Jlc3Bhc3NAcG9zdGdyZXMvcG9zdGdyZXNkYg==
  DATABASE_URL_JDBC: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXM6NTQzMi9wb3N0Z3Jlc2Ri