{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "order-management.fullname" . }}
  labels:
    {{- include "order-management.labels" . | nindent 4 }}
spec:
  jobLabel: {{ include "order-management.fullname" . }}
  namespaceSelector:
    matchNames:
    - "{{ $.Release.Namespace }}"
  selector:
    matchLabels:
      {{- include "order-management.selectorLabels" . | nindent 6 }}
  endpoints:
  - interval: 15s
    port: http
    path: /actuator/prometheus
{{- end }}      