server:
  port: 8000
  tomcat:
    max-threads: 1

spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  cache:
    type: redis
    redis:
      time-to-live: 10m
  redis:
    host: redis-master.otus-app.svc.cluster.local
    port: 6379
    password: password

logging:
  level:
    com.alexp: debug