apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "order-management.fullname" . }}
  labels:
    {{- include "order-management.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "order-management.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "order-management.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              port: http
              path: /health
            initialDelaySeconds: 40
            periodSeconds: 10
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: http
              path: /health
            initialDelaySeconds: 40
            periodSeconds: 10