replicaCount: 2

image:
  repository: plotnikov93av/otus-app
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 9000

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: arch.homework
      paths:
        path: /otusapp($|/)(.*)

postgresql:
  enabled: true
  postgresqlUsername: postgresuser
  postgresqlPassword: postgrespass
  postgresqlDatabase: postgresdb
  service:
    port: "5432"
  fullnameOverride: postgres