apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-config
data:
  DATABASE_URI: postgresql+psycopg2://myuser:passwd@postgres/myapp
  ---
apiVersion: v1
kind: Secret
metadata:
  name: hello-secret
type: Opaque
data:
  DATABASE_URI: cG9zdGdyZXNxbCtwc3ljb3BnMjovL215dXNlcjpwYXNzd2RAcG9zdGdyZXMvbXlhcHAK