{
 "title": "OM Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "RPS [direct]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method, uri) (rate(order_management_requests_seconds_count[2m]))"
    }
   ]
  },
  {
   "title": "Latency [direct]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method, uri, quantile) (order_management_requests_seconds) * 1000"
    },
    {
     "expr": "sum by (method, uri) (order_management_requests_seconds_max) * 1000"
    }
   ]
  },
  {
   "title": "Error Rate [direct]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(order_management_requests_seconds_count{status=~\"4..\"}[2m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(order_management_requests_seconds_count{status=~\"5..\"}[2m]))",
     "legendFormat": "5xx"
    }
   ]
  }
 ]
}