apiVersion: v1
name: order-management
description: A Helm chart for Kubernetes

type: application

version: 0.1.0
appVersion: v5

dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - order-management-db