replicaCount: 1

image:
  repository: otus-auth
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 9000

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: arch.homework
      paths:
        path: /auth-proxy($|/)(.*)

postgresql:
  enabled: true
  postgresqlUsername: postgresuser
  postgresqlPassword: postgrespass
  postgresqlDatabase: postgresdb
  service:
    port: "5432"
  fullnameOverride: postgres-auth
  persistence:
    size: 1Gi