server:
  port: 8000
  tomcat:
    max-threads: 1

spring:
  rabbitmq:
    host: rabbitmq.otus-app.svc
    port: 5672
    username: user
    password: xXRKnyKZ5N

logging:
  level:
    com.alexp: debug