apiVersion: v1
name: user-management
description: A Helm chart for Kubernetes

type: application

version: 0.1.0
appVersion: v1

dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - user-management-db