apiVersion: v1
kind: ConfigMap
metadata:
  name: whm-config
data:
  POSTGRES_DB: {{ .Values.postgresql.postgresqlDatabase }}
  POSTGRES_USER: {{ .Values.postgresql.postgresqlUsername }}
---
apiVersion: v1
kind: Secret
metadata:
  name: whm-secret
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXNwYXNz
  DATABASE_URI_POSTGRESQL: cG9zdGdyZXNxbDovL3Bvc3RncmVzdXNlcjpwb3N0Z3Jlc3Bhc3NAcG9zdGdyZXMtd2htL3Bvc3RncmVzZGI=
  DATABASE_URL_JDBC: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtd2htOjU0MzIvcG9zdGdyZXNkYg==